[PHP]
expose_php = Off
display_errors = On
display_startup_errors = On
log_errors = On
error_reporting = E_ALL
post_max_size = 20M
upload_max_filesize = 10M
max_execution_time = 30
max_input_time = 60
memory_limit = 64M
date.timezone = "America/Sao_Paulo"

[Session]
session.cookie_httponly = 1
session.cookie_samesite = "Lax"
session.use_strict_mode = 1
session.name = "PASCOM_SESS"

[opcache]
opcache.enable = 1
opcache.memory_consumption = 128
opcache.interned_strings_buffer = 8
opcache.max_accelerated_files = 4000
opcache.revalidate_freq = 60
opcache.validate_timestamps = 1
opcache.fast_shutdown = 1
